services:

  mysql_db:
    image: mysql:latest
    container_name: mysql_db
    restart: always
    command: --sql-mode="STRICT_TRANS_TABLES,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"  
    environment:
      MYSQL_ROOT_PASSWORD: admin123
      MYSQL_DATABASE: divest
      MYSQL_USER: divest
      MYSQL_PASSWORD: admin123
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"

volumes:
  mysql_data:
    driver: local
